Improving oneclick script

diff --git a/sui/dev/oneclicksetup b/sui/dev/oneclicksetup
--- a/sui/dev/oneclicksetup
+++ b/sui/dev/oneclicksetup
@@ -3,23 +3,11 @@
 #
 # Helper script that setups a test Atoma network environment on Sui
 #
-# Prerequisites (see the README.md):
-# - Publish the package to the Sui network
-# - Mint yourself some TOMA tokens
-#
-# Usage: ./oneclicksetup.sh <package ID>
+# Usage: ./oneclicksetup.sh
 #
 # When this script is done, we will have a model named "llama" with one echelon
 # ID 1, and a node registered to that model echelon.
 #
-
-package="${1}"
-
-# if package is not provided or does not start with 0x, exit
-if [ -z "${package}" ] || [[ ! "${package}" =~ ^0x ]]; then
-    echo "Usage: ./oneclicksetup.sh <package ID>"
-    exit 1
-fi
 
 function abs_path_to_git_root_dir() {
     # Recursively find the repo root directory so that this script can be called
@@ -38,6 +26,50 @@ function abs_path_to_git_root_dir() {
 
 entrance_dir=$(pwd)
 root_dir=$(abs_path_to_git_root_dir)
+
+cd $root_dir/sui
+
+json=$(
+    sui client publish \
+        --with-unpublished-dependencies \
+        --skip-dependency-verification \
+        --gas-budget 1000000000 \
+        --json \
+        packages/atoma
+)
+
+# if last command failed, print the error
+if [ $? -ne 0 ]; then
+    echo "${json}"
+    exit 1
+fi
+
+package=$(
+    echo "${json}" | jq -r '.objectChanges[] | select(.packageId) | .packageId'
+)
+
+if [ -z "${package}" ] || [[ ! "${package}" =~ ^0x ]]; then
+    echo "Could not publish the package. Exiting."
+    exit 1
+fi
+
+treasury=$(
+    echo "${json}" |
+        jq -r '.objectChanges[] | select(.objectType | type == "string" and startswith("0x2::coin::TreasuryCap")) | .objectId'
+)
+
+if [ -z "${treasury}" ] || [[ ! "${treasury}" =~ ^0x ]]; then
+    echo "Could not find the treasury. Exiting."
+    exit 1
+fi
+
+echo "Minting some TOMA tokens so that we can deposit collateral"
+
+sui client call \
+    --package "0x2" --module "coin" --function "mint_and_transfer" \
+    --gas-budget 10000000 \
+    --args "${treasury}" 1000000 $(sui client active-address) \
+    --type-args "${package}::toma::TOMA" || exit 1
 
 cd $root_dir/sui/dev
 
@@ -61,8 +93,6 @@ cd $root_dir/sui/dev
     --package "${package}" \
     --new-amount 1
 
-# Now we are assuming you minted yourself some TOMA tokens
-
 ./cli --wallet ~/.sui/sui_config/client.yaml \
     db register-node \
     --package "${package}"
@@ -72,6 +102,20 @@ cd $root_dir/sui/dev
     --package "${package}" \
     --model-name "llama" \
     --echelon 1
+
+echo
+echo
+echo "Package: ${package}"
+
+echo "Sending test text prompt"
+
+echo "hellow world" >/tmp/atoma-test-prompt.txt
+./cli --wallet ~/.sui/sui_config/client.yaml \
+    gate submit-example-text-prompt \
+    --package "${package}" \
+    --model-name "llama" \
+    --prompt-path /tmp/atoma-test-prompt.txt \
+    --nodes-to-sample 1
 
 # leave the caller where they started
 cd $entrance_dir
